architect:
  - h1alexbel
merge:
  script: |
    npm install
    npm run build
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/" package.json
    npm install
    npm run build
    git commit -am "${tag}"
deploy:
  script:
    - "There is no such thing as #deploy"
    - exit -1
