architect:
  - h1alexbel
merge:
  script: |
    npm install
    npm run build
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9_]+)?$ ]] || exit -1
#    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
#    mvn clean install -Prelease
deploy:
  script:
    - "There is no such thing as #deploy"
    - exit -1
